; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
monitor_dtr = 0
monitor_rts = 0
monitor_speed = 9600
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++20
    -Isrc
    -Isrc/include
    -Isrc/actions
    -Isrc/MouseIO
    -ISparkFun_TB6612FNG_Arduino_Library-master
    -ISparkFun_TB6612FNG_Arduino_Library-master/src
    -II2Cdev
    -IMPU6050
lib_deps =
  jrowberg/I2Cdevlib-Core
  jrowberg/I2Cdevlib-MPU6050
  greiman/SdFat
[env:mms-sim]
platform = native
build_flags =
    -DMMS_SIM
    -std=gnu++20
    -Isrc
    -Isrc/include
    -Isrc/actions
    -Isrc/MouseIO
    -Imms-cpp
    -ISparkFun_TB6612FNG_Arduino_Library-master
    -ISparkFun_TB6612FNG_Arduino_Library-master/src
    -II2Cdev
    -IMPU6050
build_src_filter =
    +<*>
    -<include/TeensyIO.h>
lib_deps =
  jrowberg/I2Cdevlib-Core
  jrowberg/I2Cdevlib-MPU6050